name: "CI"
on:
  push:
    branches:
      - "master"
      - "hotfix/**"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - ".gitignore"
      - "docs/**"
      - "README.md"
      - "LICENSE"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["3.1", "3.2", "3.3"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # to ensure that posts' lastmod date is available

      - name: Install dependencies for Ruby installation
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libreadline-dev zlib1g-dev git

      - name: Install Ruby version with ruby-build
        run: |
          git clone https://github.com/rbenv/ruby-build.git
          cd ruby-build
          sudo ./install.sh
          ruby-build ${{ matrix.ruby }} /opt/hostedtoolcache/Ruby/${{ matrix.ruby }}/x64

      - name: Mark Ruby installation as complete
        run: |
          touch /opt/hostedtoolcache/Ruby/${{ matrix.ruby }}/x64.complete

      - name: Verify Ruby installation
        run: ruby -v  # this should confirm Ruby is installed and the version is correct

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies and build assets
        run: npm install && npm run build

      - name: Test site
        run: bash tools/test.sh
